# Generated by Django 6.0.6 on 2026-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Write step-by-step LaTeX solution here', null=True),
        ),
    ]
