# Generated by Django 6.0.6 on 2026-07-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('9', 'Class 9th'), ('10', 'Class 10th'), ('11', 'Class 11th'), ('12', 'Class 12th')], default='10', max_length=2),
        ),
    ]
