# Generated by Django 6.0.6 on 2026-07-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_studentprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
