# Generated by Django 6.0.6 on 2026-08-04 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_studentprofile_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='mobile_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='student_class',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='student_class',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userresult',
            name='date_attempted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userresult',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userresult',
            name='subject',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Quiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('9', 'Class 9th'), ('10', 'Class 10th'), ('11', 'Class 11th'), ('12', 'Class 12th')], default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('single', 'Single Subject'), ('maths_science', 'Maths + Science Combo'), ('all_subjects', 'All Subjects Super Combo')], max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_class', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
